### ISSUE TITLE
Software freedom day wrong date

### ISSUE THREAD

**Issue by betz** [YoloSwagTeam/hackeragenda#124]
Hey,

I see our software freedom day is one week off.
https://hsbxl.be/Software_Freedom_Day_2017

Can this be deleted and reimported again?

tom

**Comment by Psycojoker** [comment]
Oups, too late, sorry :( (was really in a bad state at that time, could not handle HA correctly, sorry :/)

Still a bad idea that I'm the only one that handles that website for all Belgium...

**Comment by betz** [comment]
Hey Bram. Thanks for maintaining HA. Appreciated.
I linked HA from the Embassy website. No use of having 2 agenda's.
https://embassy.hackerspaces.be

Maybe for helping, i can ask around for participation?
