### ISSUE TITLE
Where to find CSS and JS?

### ISSUE THREAD

**Issue by ABCarnage** [YoloSwagTeam/hackeragenda#128]
Finally got the website to load. 
But not all JS en CSS gets loaded (see pic). Do I have to download these files separately?
![schermafdruk van 2018-03-30 15-28-09](https://user-images.githubusercontent.com/7237088/38139276-0233ee70-342f-11e8-8edd-1f340fe40bf3.png)

Would like to test my data. 
Thanks in advance

**Comment by Psycojoker** [comment]
Hello,

Have you followed the installation instructions? There is a command to fetch them using bower at the end https://github.com/YoloSwagTeam/hackeragenda#installation (it would be good to remove that in the future since it's not that pratical and worth it...)

**Comment by ABCarnage** [comment]
Thnx, I was too fast. Had to symlink "nodejs" to "node" (error message)
