### ISSUE TITLE
New JSON feed for HSBXL

### ISSUE THREAD

**Issue by betz** [YoloSwagTeam/hackeragenda#132]
We are archiving our mediawiki at HSBXL.
Now we have a fresh new site, build with hugo, that generates a json of upcoming events.
The new feed is: https://hsbxl.be/hackeragenda.json

Could you update this?
thanks!

**Comment by betz** [comment]
And could all the current events first be removed?
It is corrupt data...

**Comment by Psycojoker** [comment]
Done :)

**Comment by betz** [comment]
thanks ❤️
